import { absoluteUrl } from "@/lib/site-url";
import { sitemapLayout } from "@/features/seo/sitemap-layout";

// Sitemap index for the segmented sitemaps generated by app/sitemaps/sitemap.ts (Next only emits the per-id files).
export const revalidate = 3600;

export async function GET() {
  const { ids } = await sitemapLayout();
  const now = new Date().toISOString();
  const xml = `<?xml version="1.0" encoding="UTF-8"?>\n<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${ids
    .map((id) => `  <sitemap><loc>${absoluteUrl(`/sitemaps/sitemap/${id}.xml`)}</loc><lastmod>${now}</lastmod></sitemap>`)
    .join("\n")}\n</sitemapindex>\n`;
  return new Response(xml, { headers: { "Content-Type": "application/xml; charset=utf-8", "Cache-Control": "public, s-maxage=3600, stale-while-revalidate=86400" } });
}
