// Exact English DomainError messages from @cnote/identity (team) and @cnote/approvals -> keys under `approvals.errors.*` in the web
// catalogue. Kept here (not as explicit DomainError keys) so the shared `errors` namespace and the seller app are not touched.
// A message missing from this table simply shows in English.
export const APPROVAL_ERROR_KEYS: Readonly<Record<string, string>> = {
  "Your role does not allow this.": "team.roleNotAllowed",
  "You are not part of this business.": "team.roleNotAllowed",
  "Only the owner can invite an admin.": "team.onlyOwnerAdmin",
  "Only the owner can grant or remove the admin role.": "team.onlyOwnerAdmin",
  "Only the owner can remove an admin.": "team.onlyOwnerAdmin",
  "That person is already on your team.": "team.alreadyMember",
  "Your team has reached its size limit.": "team.sizeLimit",
  "Too many pending invitations. Revoke some first.": "team.tooManyInvites",
  "This invitation is not valid.": "team.inviteInvalid",
  "This invitation has expired. Ask for a new one.": "team.inviteExpired",
  "Sign in with the email address this invitation was sent to.": "team.inviteWrongAccount",
  "Transfer ownership instead of changing the owner's role.": "team.ownerRole",
  "You cannot change your own role.": "team.ownRole",
  "The owner cannot be removed. Transfer ownership first.": "team.ownerRemove",
  "Only the owner can transfer ownership.": "team.onlyOwnerTransfer",
  "Choose another member.": "team.chooseAnother",
  "Enter a valid amount.": "approvals.invalidAmount",
  "Choose approvers from your team.": "approvals.approverNotMember",
  "You have reached the limit of approval rules.": "approvals.policyLimit",
  "Invalid approval request.": "approvals.invalidRequest",
  "Say why you are rejecting.": "approvals.commentRequired",
  "This request has already been decided.": "approvals.alreadyDecided",
  "You cannot approve your own request.": "approvals.selfApproval",
  "A different person must approve each level.": "approvals.differentApprover",
  "You cannot decide this request.": "approvals.notYourApproval",
  "Choose a colleague.": "approvals.delegateSelf",
  "Only approvers can delegate.": "approvals.notApprover",
  "Choose a member of your team.": "approvals.delegateNotMember",
  "Choose a valid date range.": "approvals.delegateRange",
  "Delegation can last at most 90 days.": "approvals.delegateTooLong",
  "The approval for this quote was rejected.": "approvals.quoteRejected",
};
